name: Run tests

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Run lint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Run typecheck
        run: npm run typecheck

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.10.0
          - 21.x
    services:
      postgres:
        image: clickhouse:latest
        env:
          CLICKHOUSE_PORT: 8123
          CLICKHOUSE_USER: adonisjs
          CLICKHOUSE_PASSWORD: password
          CLICKHOUSE_DB: package
        ports:
          - 8123:8123
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
